site_name: Danceology Documentation
theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.integrate

extra_css:
  - css/style.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Codebase: 
    - Installation: codebase/installation.md
    - Build: codebase/build.md
    - Implementation Details: codebase/implementation.md
  - License: license.md
